"""
igpsport_cli.py

Minimal CLI to exercise igpsport_client.py.

Credentials come from the OS keychain (see igpsport_credentials.py), with
IGPSPORT_USER / IGPSPORT_PASSWORD env vars as a fallback. Store them once:

    uv run python igpsport_credentials.py set

Usage:
    uv run python igpsport_cli.py list
    uv run python igpsport_cli.py upload-example
    uv run python igpsport_cli.py upload-example --json
"""

from __future__ import annotations

import argparse
import json
import sys

import requests

from igpsport_client import (
    AuthError,
    IGPSportError,
    PowerTarget,
    RepeatBlock,
    Workout,
    WorkoutStep,
    create_workout,
    delete_custom_workout,
    list_custom_workouts,
    login,
)
from igpsport_credentials import CredentialsError, get_credentials


def build_example_workout() -> Workout:
    """The 4x4 we built before: warm-up, 4x(4' hard / 3' easy), cool-down."""
    blocks = [
        WorkoutStep(
            name="Warm-up",
            duration_seconds=10 * 60,
            intensity_class="WarmUp",
        ),
        RepeatBlock(
            name="Intervals",
            reps=4,
            steps=[
                WorkoutStep(
                    name="Interval",
                    duration_seconds=4 * 60,
                    intensity_class="Active",
                    power=PowerTarget(min_watts=220, max_watts=240),
                ),
                WorkoutStep(
                    name="Recovery",
                    duration_seconds=3 * 60,
                    intensity_class="Rest",
                    power=PowerTarget(min_watts=120, max_watts=140),
                ),
            ],
        ),
        WorkoutStep(
            name="Cool-down",
            duration_seconds=10 * 60,
            intensity_class="CoolDown",
        ),
    ]
    return Workout(
        title="4x4 Intervals - Example",
        description="Generated by igpsport-workouts-mcp",
        blocks=blocks,
    )


def _credentials() -> tuple[str, str]:
    try:
        return get_credentials()
    except CredentialsError as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(1)


def cmd_list(args: argparse.Namespace) -> None:
    user, password = _credentials()
    session = requests.Session()
    auth_headers = login(session, user, password)
    data = list_custom_workouts(session, auth_headers, page_size=args.page_size)
    items = (data.get("data") or {}).get("items") or []

    if args.json:
        print(json.dumps({"ok": True, "count": len(items), "items": items}, indent=2))
        return

    print(f"Custom workouts in iGPSPORT: {len(items)}")
    for item in items:
        wid = item.get("workoutId") or item.get("id")
        title = item.get("title") or "(untitled)"
        print(f"  • {wid} | {title}")


def cmd_upload_example(args: argparse.Namespace) -> None:
    user, password = _credentials()
    workout = build_example_workout()

    try:
        result = create_workout(user, password, workout)
    except (AuthError, IGPSportError) as exc:
        if args.json:
            print(json.dumps({"ok": False, "error": str(exc)}))
        else:
            print(f"✗ Error: {exc}", file=sys.stderr)
        sys.exit(1)

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(
            f"✓ Workout created: '{result['title']}' (id {result['workout_id']}, "
            f"{result['total_time_seconds']}s)"
        )


def cmd_delete(args: argparse.Namespace) -> None:
    user, password = _credentials()

    try:
        result = delete_custom_workout(user, password, args.workout_id)
    except (AuthError, IGPSportError) as exc:
        # During guess-and-test the exception carries the raw iGPSPORT response.
        if args.json:
            print(json.dumps({"ok": False, "error": str(exc)}))
        else:
            print(f"✗ Error: {exc}", file=sys.stderr)
        sys.exit(1)

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"✓ Workout {result['workout_id']} deleted")


def main() -> None:
    parser = argparse.ArgumentParser(description="iGPSPORT workout tool (standalone)")
    parser.add_argument("--json", action="store_true", help="JSON output")
    sub = parser.add_subparsers(dest="command", required=True)

    p_list = sub.add_parser("list", help="List existing custom workouts")
    p_list.add_argument("--page-size", type=int, default=50)
    p_list.set_defaults(func=cmd_list)

    p_upload = sub.add_parser("upload-example", help="Upload the example workout (4x4)")
    p_upload.set_defaults(func=cmd_upload_example)

    p_delete = sub.add_parser("delete", help="Delete a custom workout by id")
    p_delete.add_argument("workout_id", type=int, help="Workout id (see `list`)")
    p_delete.set_defaults(func=cmd_delete)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
