"""
Offline tests for the workout mapping layer.

These verify the thing that was functionally validated: the example 4x4 workout
(10' warm-up + 4x[4' @ 220-240W / 3' @ 120-140W] + 10' cool-down) maps to the
exact iGPSPORT body shape with totalTime == 2880s. No network involved.
"""

from __future__ import annotations

import pytest
from pydantic import TypeAdapter, ValidationError

from igpsport_client import PowerTarget, RepeatBlock, Workout, WorkoutStep
from igpsport_models import Block, PowerIn, StepIn, to_workout

# --- Example 4x4 as raw agent input (the validated workout) ---------------

EXAMPLE_BLOCKS_RAW = [
    {"type": "step", "name": "Warm-up", "duration_seconds": 600, "intensity_class": "WarmUp"},
    {
        "type": "repeat",
        "name": "Intervals",
        "reps": 4,
        "steps": [
            {
                "type": "step",
                "name": "Interval",
                "duration_seconds": 240,
                "intensity_class": "Active",
                "power": {"watts": [220, 240]},
            },
            {
                "type": "step",
                "name": "Recovery",
                "duration_seconds": 180,
                "intensity_class": "Rest",
                "power": {"watts": [120, 140]},
            },
        ],
    },
    {"type": "step", "name": "Cool-down", "duration_seconds": 600, "intensity_class": "CoolDown"},
]

_blocks_adapter = TypeAdapter(list[Block])


def _parse(raw):
    return _blocks_adapter.validate_python(raw)


# --- total time -----------------------------------------------------------

def test_example_total_time_is_2880():
    workout = to_workout("4x4 Intervals", "", _parse(EXAMPLE_BLOCKS_RAW))
    # 600 + 4*(240+180) + 600 = 600 + 1680 + 600 = 2880
    assert workout.total_time_seconds() == 2880


def test_example_body_shape():
    workout = to_workout(
        "4x4 Intervals", "Generated by igpsport_tool", _parse(EXAMPLE_BLOCKS_RAW)
    )
    body = workout.to_igps_body()["data"]

    assert body["totalTime"] == 2880
    assert body["workoutType"] == "bike"
    assert body["sportBigType"] == 1
    assert body["allowDeletion"] is True
    assert "id" not in body  # not an edit

    structure = body["structure"]
    assert [b["type"] for b in structure] == ["Step", "Repetition", "Step"]

    warmup = structure[0]
    assert warmup["intensityClass"] == "WarmUp"
    assert warmup["length"] == {"unit": "Second", "value": 600}
    assert "intensityTarget" not in warmup  # no power target

    rep = structure[1]
    assert rep["length"] == {"unit": "Repetition", "value": 4}
    assert [s["type"] for s in rep["steps"]] == ["Step", "Step"]
    interval = rep["steps"][0]
    assert interval["intensityClass"] == "Active"
    assert interval["intensityTarget"] == {
        "unit": "PowerCustom",
        "value": 0,
        "minValue": 220,
        "maxValue": 240,
    }


# --- power targets --------------------------------------------------------

def test_pct_ftp_power_target():
    step = StepIn(
        name="Threshold",
        duration_seconds=300,
        intensity_class="Active",
        power=PowerIn(pct_ftp=(90, 100)),
    )
    target = step.to_step().to_igps()["intensityTarget"]
    assert target == {"unit": "PercentOfFTP", "minValue": 90, "maxValue": 100}


def test_power_requires_exactly_one_unit():
    with pytest.raises(ValidationError):
        PowerIn(watts=(200, 250), pct_ftp=(80, 90))
    with pytest.raises(ValidationError):
        PowerIn()


def test_power_range_must_be_ordered():
    with pytest.raises(ValidationError):
        PowerIn(watts=(250, 200))


# --- open duration --------------------------------------------------------

def test_open_duration_step_omits_length():
    step = StepIn(name="Free ride", intensity_class="Active", open_duration=True)
    igps = step.to_step().to_igps()
    assert igps["openDuration"] == "true"
    assert "length" not in igps


def test_step_without_duration_or_open_is_rejected():
    with pytest.raises(ValidationError):
        StepIn(name="Bad step", intensity_class="Active")


# --- edit vs create -------------------------------------------------------

def test_edit_sets_id():
    workout = to_workout("Edited", "", _parse(EXAMPLE_BLOCKS_RAW), edit_workout_id=12345)
    body = workout.to_igps_body()["data"]
    assert body["id"] == "12345"


# --- discriminated union --------------------------------------------------

def test_repeat_block_requires_non_empty_steps():
    with pytest.raises(ValidationError):
        _parse([{"type": "repeat", "name": "Empty", "reps": 3, "steps": []}])


def test_unknown_block_type_is_rejected():
    with pytest.raises(ValidationError):
        _parse([{"type": "tempo", "name": "Nope"}])
