"""
Offline tests for the workout mapping layer.

These verify the thing that was functionally validated: the example 4x4 workout
(10' warm-up + 4x[4' @ 220-240W / 3' @ 120-140W] + 10' cool-down) maps to the
exact iGPSPORT body shape with totalTime == 2880s. No network involved.
"""

from __future__ import annotations

import pytest
from pydantic import TypeAdapter, ValidationError

import igpsport_client
from igpsport_client import (
    IGPS_WORKOUT_DELETE_URL,
    HeartRateTarget,
    IGPSportError,
    PowerTarget,
    RepeatBlock,
    Workout,
    WorkoutStep,
    delete_workout,
)
from igpsport_models import Block, HeartRateIn, PowerIn, StepIn, to_workout

# --- Example 4x4 as raw agent input (the validated workout) ---------------

EXAMPLE_BLOCKS_RAW = [
    {"type": "step", "name": "Warm-up", "duration_seconds": 600, "intensity_class": "WarmUp"},
    {
        "type": "repeat",
        "name": "Intervals",
        "reps": 4,
        "steps": [
            {
                "type": "step",
                "name": "Interval",
                "duration_seconds": 240,
                "intensity_class": "Active",
                "power": {"watts": [220, 240]},
            },
            {
                "type": "step",
                "name": "Recovery",
                "duration_seconds": 180,
                "intensity_class": "Rest",
                "power": {"watts": [120, 140]},
            },
        ],
    },
    {"type": "step", "name": "Cool-down", "duration_seconds": 600, "intensity_class": "CoolDown"},
]

_blocks_adapter = TypeAdapter(list[Block])


def _parse(raw):
    return _blocks_adapter.validate_python(raw)


# --- total time -----------------------------------------------------------

def test_example_total_time_is_2880():
    workout = to_workout("4x4 Intervals", "", _parse(EXAMPLE_BLOCKS_RAW))
    # 600 + 4*(240+180) + 600 = 600 + 1680 + 600 = 2880
    assert workout.total_time_seconds() == 2880


def test_example_body_shape():
    workout = to_workout(
        "4x4 Intervals", "Generated by igpsport_tool", _parse(EXAMPLE_BLOCKS_RAW)
    )
    body = workout.to_igps_body()["data"]

    assert body["totalTime"] == 2880
    assert body["workoutType"] == "bike"
    assert body["sportBigType"] == 1
    assert body["allowDeletion"] is True
    assert "id" not in body  # not an edit

    structure = body["structure"]
    assert [b["type"] for b in structure] == ["Step", "Repetition", "Step"]

    warmup = structure[0]
    assert warmup["intensityClass"] == "WarmUp"
    assert warmup["length"] == {"unit": "Second", "value": 600}
    assert "intensityTarget" not in warmup  # no power target

    rep = structure[1]
    assert rep["length"] == {"unit": "Repetition", "value": 4}
    assert [s["type"] for s in rep["steps"]] == ["Step", "Step"]
    interval = rep["steps"][0]
    assert interval["intensityClass"] == "Active"
    assert interval["intensityTarget"] == {
        "unit": "PowerCustom",
        "value": 0,
        "minValue": 220,
        "maxValue": 240,
    }


# --- power targets --------------------------------------------------------

def test_pct_ftp_power_target():
    step = StepIn(
        name="Threshold",
        duration_seconds=300,
        intensity_class="Active",
        power=PowerIn(pct_ftp=(90, 100)),
    )
    target = step.to_step().to_igps()["intensityTarget"]
    assert target == {"unit": "PercentOfFTP", "minValue": 90, "maxValue": 100}


def test_power_requires_exactly_one_unit():
    with pytest.raises(ValidationError):
        PowerIn(watts=(200, 250), pct_ftp=(80, 90))
    with pytest.raises(ValidationError):
        PowerIn()


def test_power_range_must_be_ordered():
    with pytest.raises(ValidationError):
        PowerIn(watts=(250, 200))


# --- heart-rate targets ---------------------------------------------------

def test_bpm_range_maps_to_heart_rate_custom():
    step = StepIn(
        name="Tempo",
        duration_seconds=1200,
        intensity_class="Active",
        heart_rate=HeartRateIn(bpm=(145, 160)),
    )
    target = step.to_step().to_igps()["intensityTarget"]
    assert target == {"unit": "HeartRateCustom", "minValue": 145, "maxValue": 160}


def test_hr_zone_maps_to_heart_rate_value():
    step = StepIn(
        name="Z3",
        duration_seconds=600,
        intensity_class="Active",
        heart_rate=HeartRateIn(hr_zone=3),
    )
    target = step.to_step().to_igps()["intensityTarget"]
    assert target == {"unit": "HeartRate", "value": 3}


def test_heart_rate_requires_exactly_one_form():
    with pytest.raises(ValidationError):
        HeartRateIn(bpm=(140, 160), hr_zone=3)
    with pytest.raises(ValidationError):
        HeartRateIn()


def test_hr_zone_out_of_range_is_rejected():
    with pytest.raises(ValidationError):
        HeartRateIn(hr_zone=6)


def test_bpm_range_must_be_ordered():
    with pytest.raises(ValidationError):
        HeartRateIn(bpm=(160, 140))


def test_step_cannot_target_both_power_and_heart_rate():
    with pytest.raises(ValidationError):
        StepIn(
            name="Both",
            duration_seconds=300,
            intensity_class="Active",
            power=PowerIn(watts=(200, 250)),
            heart_rate=HeartRateIn(bpm=(150, 165)),
        )


def test_client_step_rejects_both_targets_directly():
    step = WorkoutStep(
        name="Both",
        duration_seconds=300,
        power=PowerTarget(min_watts=200, max_watts=250),
        heart_rate=HeartRateTarget(min_bpm=150, max_bpm=165),
    )
    with pytest.raises(ValueError):
        step.to_igps()


def test_hr_workout_body_shape():
    blocks_raw = [
        {"type": "step", "name": "Warm-up", "duration_seconds": 600, "intensity_class": "WarmUp"},
        {"type": "step", "name": "Tempo", "duration_seconds": 1200, "intensity_class": "Active",
         "heart_rate": {"bpm": [145, 160]}},
        {"type": "step", "name": "Cool-down", "duration_seconds": 300, "intensity_class": "CoolDown"},
    ]
    workout = to_workout("HR Tempo", "", _parse(blocks_raw))
    body = workout.to_igps_body()["data"]
    assert body["totalTime"] == 2100
    assert body["structure"][1]["intensityTarget"] == {
        "unit": "HeartRateCustom",
        "minValue": 145,
        "maxValue": 160,
    }


# --- open duration --------------------------------------------------------

def test_open_duration_step_omits_length():
    step = StepIn(name="Free ride", intensity_class="Active", open_duration=True)
    igps = step.to_step().to_igps()
    assert igps["openDuration"] == "true"
    assert "length" not in igps


def test_step_without_duration_or_open_is_rejected():
    with pytest.raises(ValidationError):
        StepIn(name="Bad step", intensity_class="Active")


# --- edit vs create -------------------------------------------------------

def test_edit_sets_id():
    workout = to_workout("Edited", "", _parse(EXAMPLE_BLOCKS_RAW), edit_workout_id=12345)
    body = workout.to_igps_body()["data"]
    assert body["id"] == "12345"


# --- delete (offline request-shape checks) --------------------------------

class _FakeResponse:
    def __init__(self, payload, ok=True, status_code=200, text=""):
        self._payload = payload
        self.ok = ok
        self.status_code = status_code
        self.text = text

    def json(self):
        return self._payload


class _FakeSession:
    """Captures the last POST so we can assert URL + params + body without a network."""

    def __init__(self, response):
        self._response = response
        self.last_url = None
        self.last_params = None
        self.last_json = None
        self.last_headers = None

    def post(self, url, params=None, json=None, headers=None):
        self.last_url = url
        self.last_params = params
        self.last_json = json
        self.last_headers = headers
        return self._response


def test_delete_builds_expected_request():
    # Matches the request captured from the iGPSPORT app: id as query param,
    # empty body, POST to CustomWorkOutDel.
    session = _FakeSession(_FakeResponse({"code": 0, "data": True}))
    result = delete_workout(session, {"Authorization": "Bearer x"}, 12345)

    assert session.last_url == IGPS_WORKOUT_DELETE_URL
    assert session.last_url.endswith("/WorkOut/CustomWorkOutDel")
    assert session.last_params == {"id": 12345}
    assert session.last_json == {}
    assert session.last_headers == {"Authorization": "Bearer x"}
    assert result == {"code": 0, "data": True}


def test_delete_raises_on_nonzero_code():
    session = _FakeSession(_FakeResponse({"code": 1, "msg": "not found"}))
    with pytest.raises(IGPSportError):
        delete_workout(session, {}, 999)


def test_delete_raises_on_http_error():
    session = _FakeSession(_FakeResponse({}, ok=False, status_code=404, text="Not Found"))
    with pytest.raises(IGPSportError) as exc:
        delete_workout(session, {}, 1)
    assert "404" in str(exc.value)


# --- discriminated union --------------------------------------------------

def test_repeat_block_requires_non_empty_steps():
    with pytest.raises(ValidationError):
        _parse([{"type": "repeat", "name": "Empty", "reps": 3, "steps": []}])


def test_unknown_block_type_is_rejected():
    with pytest.raises(ValidationError):
        _parse([{"type": "tempo", "name": "Nope"}])
